version: '3.4'

services:
  govwifi-sessions-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: govwifi_local
    healthcheck:
      test: "mysql --user=root --password=testpassword -e 'SELECT 1'"

  govwifi-user-details-db:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: govwifi_local
    healthcheck:
      test: "mysql --user=root --password=testpassword -e 'SELECT 1'"

  govwifi-fake-s3:
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
    volumes:
      - ./fake-s3:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./fake-s3/localstack-init:/docker-entrypoint-initaws.d

  govwifi-frontend-local:
    build:
      context: .frontend
    depends_on:
      - govwifi-authentication-api-local
      - govwifi-logging-api-local
      - govwifi-frontend-raddb-local
    environment:
      AUTHORISATION_API_BASE_URL: "http://govwifi-authentication-api-local:8080"
      LOGGING_API_BASE_URL: "http://govwifi-logging-api-local:8080"
      RADIUS_CONFIG_WHITELIST_URL: "http://govwifi-fake-s3:8080/clients.conf"
      HEALTH_CHECK_RADIUS_KEY: RrPTmh8s9NZFenAFx2kG
      HEALTH_CHECK_SSID: GovWifi
      HEALTH_CHECK_IDENTITY: DSLPR
      HEALTH_CHECK_PASSWORD: SharpRegainDetailed
      RADIUSD_PARAMS: "-X"
    volumes:
      - raddb-certs:/etc/raddb/certs 

  govwifi-frontend-raddb-local:
    build:
      context: .frontend
      dockerfile: Dockerfile.raddb
    command: tail -f /dev/null
    healthcheck:
      test: CMD test -f /etc/raddb/certs/server.key
    depends_on:
      - govwifi-fake-s3
    environment:
      DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: testkey
      AWS_SECRET_ACCESS_KEY: testsecret
      WHITELIST_BUCKET: s3://test-bucket
      CERT_STORE_BUCKET: s3://test-bucket
      ENDPOINT_URL: "http://govwifi-fake-s3:4572"
    volumes:
      - raddb-certs:/etc/raddb/certs

  govwifi-authentication-api-local:
    build:
      context: .authentication-api
      args:
        BUNDLE_INSTALL_CMD: bundle install --without test --no-cache --jobs 8
    depends_on:
      - govwifi-user-details-db
    environment:
      DB_HOSTNAME: govwifi-user-details-db
      DB_USER: root
      DB_PASS: testpassword
      DB_NAME: govwifi_local

  govwifi-logging-api-local:
    build:
      context: .logging-api
      args:
        BUNDLE_INSTALL_CMD: bundle install --without test --no-cache --jobs 8
    depends_on:
      - govwifi-sessions-db
    environment:
      DB_HOSTNAME: govwifi-sessions-db
      DB_USER: root
      DB_PASS: testpassword
      DB_NAME: govwifi_local
      USER_DB_NAME: govwifi_local
      USER_DB_PASS: testpassword
      USER_DB_USER: root
      USER_DB_HOSTNAME: govwifi-user-details-db

  govwifi-test:
    build:
      context: acceptance_tests
    depends_on:
      - govwifi-sessions-db
      - govwifi-frontend-local
    environment:
      DB_HOSTNAME: govwifi-sessions-db
      DB_NAME: govwifi_local
      DB_USER: root
      DB_PASS: testpassword
      USER_DB_NAME: govwifi_local
      USER_DB_PASS: testpassword
      USER_DB_USER: root
      USER_DB_HOSTNAME: govwifi-user-details-db
      FRONTEND_CONTAINER: govwifi-frontend-local
      RADIUS_KEY: testingradiussecret

volumes:
  raddb-certs:
